apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentic-net-gateway
spec:
  gatewayClassName: cloud-provider-kind
  listeners:
  - protocol: HTTP
    port: 10001
    name: agentic-net-gateway-listener1
    allowedRoutes:
      namespaces:
        from: Same
---
# Define a Backend resource for server1, which runs in the K8s cluster.
apiVersion: agentic.networking.x-k8s.io/v1alpha1
kind: Backend
metadata:
  name: mcp-server1
spec:
  type: MCP
  mcp:
    serviceName: server1-svc
    port: 9000
    path: /mcp
---
# Define a Backend resource for mcp.deepwiki.com.
apiVersion: agentic.networking.x-k8s.io/v1alpha1
kind: Backend
metadata:
  name: mcp-server2
spec:
  type: MCP
  mcp:
    hostname: mcp.deepwiki.com
    port: 443
    path: /mcp
---
apiVersion: agentic.networking.x-k8s.io/v1alpha1
kind: AuthPolicy
metadata:
  name: auth-policy-server1
spec:
  # AuthPolicy targets a single HTTPRoute.
  targetRef:
    group: gateway.networking.x-k8s.io
    kind: Backend
    name: mcp-server1
  rules:
  - source:
      serviceAccounts:
      - "system:serviceaccount:default:sa1"
    tools:
    - "add"
    - "subtract"
  - source:
      serviceAccounts:
      - "system:serviceaccount:default:sa2"
    tools:
    - "subtract"
---
apiVersion: agentic.networking.x-k8s.io/v1alpha1
kind: AuthPolicy
metadata:
  name: auth-policy-server2
spec:
  targetRef:
    group: gateway.networking.x-k8s.io
    kind: Backend
    name: mcp-server2
  rules:
  - source:
      serviceAccounts:
      - "system:serviceaccount:default:sa2"
    tools:
    - "read_wiki_structure"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-server1
spec:
  parentRefs:
  - name: agentic-net-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /mcp-server1/mcp
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /mcp
    backendRefs:
    - name: mcp-server1 # server1 running in the Kubernetes cluster
      group: agentic.networking.x-k8s.io
      kind: Backend
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-server2
spec:
  parentRefs:
  - name: agentic-net-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /mcp-server2/mcp
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /mcp
    backendRefs:
    - name: mcp-server2
      group: agentic.networking.x-k8s.io
      kind: Backend
