apiVersion: v1
kind: ServiceAccount
metadata:
  name: adk-agent-sa
  namespace: agent-spiffe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-agent
  namespace: agent-spiffe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-agent
  template:
    metadata:
      labels:
        app: adk-agent
    spec:
      serviceAccountName: adk-agent-sa
      containers:
        - name: adk-agent
          imagePullPolicy: Always
          image: docker.io/hmeng/agent-spiffe:v25
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "128Mi"
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "128Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/trust-bundle.pem
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/trust-bundle.pem
            - name: CLIENT_CERT_FILE
              value: /var/run/secrets/spiffe.io/tls.crt
            - name: CLIENT_KEY_FILE
              value: /var/run/secrets/spiffe.io/tls.key
            - name: PORT
              value: "8080"
            - name: ENVOY_SERVICE
              value: "envoy-service.envoy-gateway-system.svc.cluster.local:10001"
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: google-api-key
          volumeMounts:
          - mountPath: /var/run/secrets/spiffe.io
            name: spiffe
          - mountPath: /etc/ssl/certs/trust-bundle.pem
            subPath: trust-bundle.pem
            name: cert-bundle
            readOnly: true
      volumes:
      - csi:
          driver: spiffe.csi.cert-manager.io
          readOnly: true
        name: spiffe
      - configMap:
          defaultMode: 420
          name: example-bundle
        name: cert-bundle
---
apiVersion: v1
kind: Service
metadata:
  name: adk-agent-svc
  namespace: agent-spiffe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: adk-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-requester
  namespace: agent-spiffe
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create", "get", "list", "watch"] # Ensure these are all present
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa1-cert-manager-requester
  namespace: agent-spiffe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-requester
subjects:
- kind: ServiceAccount
  name: adk-agent-sa
  namespace: agent-spiffe