---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:public-info-jwks
rules:
- nonResourceURLs:
  - "/openid/v1/jwks" # The endpoint Envoy is trying to fetch
  verbs:
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:public-info-jwks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:public-info-jwks
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated # Grant permission to all anonymous users
