apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-trust-config
  namespace: agent-spiffe
data:
  spiffe_trust.yaml: |
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: "spiffe_trust"
      validation_context:
        trusted_ca:
          filename: "/run/agent-identity-mtls/cluster.local.trust-bundle.pem"
