apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-identity-config
  namespace: agent-spiffe
data:
  spiffe_identity.yaml: |
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: "spiffe_identity"
      tls_certificate:
        certificate_chain:
          filename: "/var/run/secrets/spiffe.io/cred-bundle.pem"
        private_key:
          filename: "/var/run/secrets/spiffe.io/cred-bundle.pem"
