apiVersion: v1
kind: ServiceAccount
metadata:
  name: adk-agent-sa
  namespace: agent-spiffe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-agent
  namespace: agent-spiffe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adk-agent
  template:
    metadata:
      labels:
        app: adk-agent
    spec:
      serviceAccountName: adk-agent-sa
      containers:
        - name: adk-agent
          imagePullPolicy: Always
          image: docker.io/hmeng/agent:v30
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "128Mi"
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "128Mi"
          ports:
            - containerPort: 8080
              name: adk-agent
          env:
            - name: PORT
              value: "8080"
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: google-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: adk-agent-svc
  namespace: agent-spiffe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: adk-agent
    - port: 10001
      targetPort: 10001
      name: envoy
  selector:
    app: adk-agent
